### ISSUE TITLE
What is "spi_ch" on the configuration parameters?

### ISSUE THREAD

**Issue by IagoMrt** [xg590/Learn_SX1276#1]
Hello , first of all thank you and congratulations for the amazing job u have done with the library.

Everything is cristal clear on the code except for the part in which u define the spi interface, to be more precise the "spi_ch" parameter, I have been checking the internet trying to figure out what does stands for with no success.

Could you please give me so information about that? right now I am using a lopy4 device ( esp32 espressiff + sx1276 lora module ) so the spi varies, and could not find any reference for that specific parameter.

Thanks for all.

**Comment by xg590** [comment]
SPI_CH is an argument in the MicroPython reserved for board with more than one SPI interface like ESP32 or RPi Pico. Your LoRa chip was wired to specific SPI pins of board and then told MicroPython the SPI interface you used by specifying the SPI CHannel number.  @LagoMrt

**Comment by xg590** [comment]
Ask if there is still a question

**Comment by IagoMrt** [comment]
Thanks for the help now is all cristal clear, will keep trying to set up the library on the device and make some test, in case I have future doubts will post them.

Again thanks for your help.
